### ISSUE TITLE
try to implement, not working 

### ISSUE THREAD

**Issue by bwa616** [horizon-institute/artcodes-cordova#1]
Hello , i try to use this plugin in one app , im using jquery in an html app, the code i used was:
`$("#artcode1").on("click", function () {
        Artcodes.scan({
            name: "Test Experience",
            actions: [{
                codes: ["1:2:3:4"]
            }]
        }, function (marker) {
            alert(marker);
        });
    });`

but nothing happened, is it something wrong?

**Comment by wwpreston** [comment]
Hi. That code looks OK. So that we can further help you could you please let us know the following:
- What version of Cordova are you using?
- What platform are you testing this on? (and version)
- Are you using a real device or emulator?
- Could you clarify what you mean by "nothing happened"? (e.g. nothing appeared on the screen, or the scan screen appeared but would not scan anything, or the callback function was not called after scanning)
- Do you get any exceptions? Try changing your code to
~~~~
$("#artcode1").on("click", 
    function () { 
        try {
            Artcodes.scan(
                { name: "Test Experience", actions: [{ codes: ["1:2:3:4"] }] }, 
                function (marker) { alert(marker); }
            ); 
        } catch (err) { alert(err.message) }
    }
);
~~~~

**Comment by bwa616** [comment]
Hello again , thank you for your fast response, im using cordova 6.5.0 , in android os, using a motorola moto g4 running android 6.0.1, and debugging using the chrome device inspector.

i followed the instructions and installed the plugin using cordova instead of ionic:

`cordova plugin add https://github.com/horizon-institute/artcodes-cordova.git`

I have tried the code you suggested and it shows an alert saying "Artcodes is not defined"

is there a way i can test it using the console of the chrome inspector?

**Comment by bwa616** [comment]
Hey again! the code is working now, the problem was because I forgot to add a line of code to my html file:
`<script type="text/javascript" src="cordova.js"></script>`

And also the order of adding the plugin and generating the code for android.

 Thank you for your attention and sorry for the trouble

**Comment by wwpreston** [comment]
Glad it worked out. Apologies for the delay in only getting back to this today. If you have any other problems let us know.
